version: '3.4'

services:
  stelio-bot:
    image: kpfecteau/stelio-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
